# Generated by Django 4.0.4 on 2022-04-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201122_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ventilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventilator_number', models.CharField(max_length=50)),
                ('occupied', models.BooleanField()),
            ],
        ),
    ]
