# Generated by Django 4.0.4 on 2022-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ventilator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_req', models.TextField(blank=True, max_length=100, null=True)),
                ('occupied', models.BooleanField()),
            ],
        ),
    ]
