# Generated by Django 4.0.4 on 2022-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.TextField(blank=True, max_length=100, null=True)),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pending',
        ),
    ]
